name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - main
  release: 
    types: [ published, edited]
    branches:
      - main
#   pull_request:
#     branches: [ main ]
  push:  
    tags:
      - qa*
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 13.233.51.77
        username: ubuntu
        key: ${{secrets.PRIVATE_KEY}}
        port: 22
        script: |
          whoami
          git switch main
          git fetch
          git merge
        
