name: CI/CD Pipeline

on:
  release: 
    types: [ published, edited]
    branches:
      - main
#   pull_request:
#     branches: [ main ]
  push:  
    tags:
      - qa*
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
#     if: github.event_name == 'push'
#     if: startsWith(github.ref, 'refs/tags/')
    if: ${{ github.ref == 'refs/tags/qa*' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        # Run your test commands here
        echo "tag created"

  deploy:
    runs-on: ubuntu-latest
#     needs: test
    if: github.event_name == 'release'
#     if: startsWith(github.ref, 'refs/release/types')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy application
      run: |
        # Run your deployment commands here
        echo "released deployments"
