name: CI/CD Pipeline

on:
  release:
    types: [ published, edited]
  push:  
    tags:
      - qa*
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'tags'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        # Run your test commands here
        echo "tag created"

  deploy:
    runs-on: ubuntu-latest
#     needs: test
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy application
      run: |
        # Run your deployment commands here
        echo "released deployments"
